VALUE_TRAP_PE_RATIO_MAX = 12.0
VALUE_TRAP_DEBT_TO_EQUITY_MAX = 1.0
VALUE_TRAP_RETURN_ON_CAPITAL_MIN = 0.08
VALUE_TRAP_FLAG_COUNT_MIN = 3

INFLATION_SPIKE_RATE_MIN = 3.0
INFLATION_MARGIN_CHANGE_FLOOR = -0.01

DERIVATIVES_EXPOSURE_MODERATE_MIN = 1.0
DERIVATIVES_EXPOSURE_HIGH_MIN = 3.0
LEVEL3_ASSETS_MODERATE_MIN = 0.05
LEVEL3_ASSETS_HIGH_MIN = 0.15

BEHAVIORAL_HOLDING_PERIOD_MIN_YEARS = 1.0
BEHAVIORAL_HIGH_RISK_FLAG_COUNT_MIN = 2

BUSINESS_MODEL_RECURRING_REVENUE_MIN = 0.7
BUSINESS_MODEL_ASSET_HEAVY_GROSS_MARGIN_MAX = 0.25
BUSINESS_MODEL_ASSET_HEAVY_CAPITAL_INTENSITY_MIN = 0.10
BUSINESS_MODEL_ASSET_LIGHT_GROSS_MARGIN_MIN = 0.50

GOODWILL_ECONOMIC_MULTIPLE_MAX = 5.0
GOODWILL_ECONOMIC_RETURN_ON_TANGIBLE_ASSETS_MIN = 0.12
GOODWILL_MIXED_MULTIPLE_MAX = 8.0
GOODWILL_MIXED_RETURN_ON_TANGIBLE_ASSETS_MIN = 0.08

DURABILITY_RETURN_ON_CAPITAL_MIN = 0.12

UNDERWRITING_EXCELLENT_COMBINED_RATIO_MAX = 95.0
UNDERWRITING_DISCIPLINED_COMBINED_RATIO_MAX = 100.0

CONSUMER_BRAND_GROSS_MARGIN_MIN = 0.35
MEDIA_SUBSCRIPTION_REVENUE_MIN = 0.5
MEDIA_AD_REVENUE_MAX = 0.5
MEDIA_CHURN_MAX = 0.10
UTILITY_REGULATED_ASSET_RATIO_MIN = 0.7
UTILITY_DEBT_TO_EBITDA_MAX = 5.0
UTILITY_ALLOWED_ROE_MIN = 0.09
RAILWAY_OPERATING_RATIO_MAX = 0.65
RAILWAY_MAINTENANCE_CAPEX_RATIO_MAX = 0.6
TECH_RECURRING_REVENUE_MIN = 0.6
TECH_NET_REVENUE_RETENTION_MIN = 1.0
TECH_STOCK_COMP_RATIO_MAX = 0.15
AVOID_INDUSTRY_COMMODITY_EXPOSURE_MIN = 0.7
AVOID_INDUSTRY_LEVERAGE_RATIO_MIN = 4.0
AVOID_INDUSTRY_PRICING_POWER_MAX = 0.3
AVOID_INDUSTRY_RED_FLAG_COUNT_MIN = 2

MR_MARKET_FEAR_DRAWDOWN_MAX = -0.20
MR_MARKET_FEAR_DISTANCE_FROM_MA_MAX = -0.10
MR_MARKET_GREED_DRAWDOWN_MIN = -0.05
MR_MARKET_GREED_DISTANCE_FROM_MA_MIN = 0.10
TRADING_DAYS_PER_YEAR = 252

LONG_TERM_STRONG_YEARS_MIN = 5.0
LONG_TERM_STRONG_EXCESS_RETURN_MIN = 0.02
LONG_TERM_ACCEPTABLE_YEARS_MIN = 3.0

LATTICE_BROAD_SCORE_MIN = 0.75
LATTICE_DEVELOPING_SCORE_MIN = 0.5
INDEPENDENT_THINKING_EVIDENCE_MIN = 0.7
INDEPENDENT_THINKING_VALUATION_GAP_MIN = 0.15
PATIENCE_HOLDING_PERIOD_MIN_YEARS = 3.0
PATIENCE_TURNOVER_RATIO_MAX = 0.25

DEEP_DISCOUNT_MARGIN_MIN = 0.25
DISCOUNT_MARGIN_MIN = 0.10
CAPITAL_ALLOCATION_STRONG_FCF_TO_DEBT_MIN = 0.25
SPECIAL_INSTRUMENT_COUPON_RATE_MIN = 0.08
SPECIAL_INSTRUMENT_CONVERSION_DISCOUNT_MIN = 0.10
SPECIAL_INSTRUMENT_COLLATERAL_COVERAGE_MIN = 1.0

CULTURE_EMPLOYEE_TURNOVER_MAX = 0.15
CULTURE_INSIDER_OWNERSHIP_MIN = 0.05
CULTURE_RESTRUCTURINGS_MAX = 1
ACQUISITION_PURCHASE_MULTIPLE_MAX = 12.0
ACQUISITION_ROIC_MIN = 0.12
GOVERNANCE_INSIDER_OWNERSHIP_MIN = 0.05
GOVERNANCE_STRONG_SCORE_MIN = 3

FOCUS_INVESTING_TOP_THREE_WEIGHT_MIN = 0.50
EFFICIENT_MARKET_EXCESS_RETURN_MAX = 0.02
EFFICIENT_MARKET_TRACKING_ERROR_MAX = 0.05
MARKET_FORECAST_USEFUL_ERROR_MAX = 0.05
UNDERVALUED_MARGIN_MIN = 0.25
